### ISSUE TITLE
Have you considered adding a license?

### ISSUE THREAD

**Issue by hellodword** [imSanjaySoni/NoteApp-Clean-Architecture#15]
This project looks cute, and I'm interested in utilizing your project to create an app.

Are you considering applying a permissive license to the project? This would help clarify the terms of its use. MIT would be great :)

Thanks.

**Comment by imSanjaySoni** [comment]
Thanks for your interest, I have added the MIT license. 

[commit](https://github.com/imSanjaySoni/NoteApp-Clean-Architecture/commit/4963b7cda1ebe23b59aea076caef5f3d33ea8069)
