### ISSUE TITLE
Avoid catches without on clauses

### ISSUE THREAD

**Issue by t1ooo** [imSanjaySoni/NoteApp-Clean-Architecture#4]
https://dart-lang.github.io/linter/lints/avoid_catches_without_on_clauses.html
https://dart-lang.github.io/linter/lints/avoid_catching_errors.html

```dart
void main() {
  try {
    throw OutOfMemoryError();
  } catch (e) {
    print(e);
  }
  print('everything is fine');
}
```

**Comment by imSanjaySoni** [comment]
Thanks for noticing. it is fixed with [this PR](https://github.com/imSanjaySoni/NoteApp-Clean-Architecture/pull/8)
